language: java
sudo : required
dist : trusty
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - python
    - oracle-java8-installer

before_install:
- rm ~/.m2/settings.xml

install:
  - sudo pip install awscli

jobs: 
  include:
    - stage: tests 
      name: unit
      script: 
        - mvn clean install -DskipTests=false -q --update-snapshots -f ./dhis-2/pom.xml
        - mvn clean install -DskipTests=false -q --update-snapshots -f ./dhis-2/dhis-web/pom.xml
        
    - name: integration
      script: 
        - mvn clean install -Pintegration -f ./dhis-2/pom.xml

#Uploads the built .war file to eHA's S3 so that the test env can run from it  
deploy:
  - provider: script
    skip_cleanup: true
    script: aws s3 cp ./dhis-2/dhis-web/dhis-web-portal/target/dhis.war s3://eha-eidsr-sl/dhis2_wars/dhis2_eha-sms.war
    on:
      branch: eha-sms

after_deploy:
  - aws s3api put-object-acl --acl public-read --bucket eha-eidsr-sl --key dhis2_wars/dhis2_eha-sms.war

branches:
  only:
  - eha-sms
