language: java
sudo : required
dist : trusty
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - python
    - oracle-java8-installer

before_install:
- rm ~/.m2/settings.xml

install:
  - pip install awscli

# script:
#   -  mvn clean install -DskipTests=false -DargLine="-Xmx512m -Xms256m" -q --update-snapshots -f  ./dhis-2/pom.xml
#   -  mvn clean install -DskipTests=false -DargLine="-Xmx512m -Xms256m" -q --update-snapshots -f ./dhis-2/dhis-web/pom.xml
# Uploads the built .war file to eHA's S3 so that the test env can run from it  

before_deploy:
  - aws s3 cp README.md s3://eha-eidsr-sl/dhis2_wars/

branches:
  only:
  - build-travis
